# Generated by Django 5.2 on 2025-05-19 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
        ("productos", "0002_catalogo_producto_catalogo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="traspaso",
            name="cantidad",
        ),
        migrations.RemoveField(
            model_name="traspaso",
            name="producto",
        ),
        migrations.CreateModel(
            name="TraspasoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="traspaso_items",
                        to="productos.producto",
                    ),
                ),
                (
                    "traspaso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventario.traspaso",
                    ),
                ),
            ],
        ),
    ]
