# Generated by Django 5.2.1 on 2025-05-27 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0001_initial"),
        ("tiendas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logauditoria",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Log de Auditoría",
                "verbose_name_plural": "Logs de Auditoría",
            },
        ),
        migrations.AddField(
            model_name="logauditoria",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="logauditoria",
            name="modelo_afectado",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="logauditoria",
            name="objeto_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="logauditoria",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="logauditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("CREATE", "Crear"),
                    ("UPDATE", "Actualizar"),
                    ("DELETE", "Eliminar"),
                    ("LOGIN", "Iniciar Sesión"),
                    ("LOGOUT", "Cerrar Sesión"),
                    ("BACKUP", "Respaldo"),
                    ("EXPORT", "Exportar"),
                    ("IMPORT", "Importar"),
                    ("CONFIG", "Configuración"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ConfiguracionSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=100, unique=True)),
                ("valor", models.TextField()),
                ("descripcion", models.TextField(blank=True)),
                (
                    "tipo_dato",
                    models.CharField(
                        choices=[
                            ("string", "Texto"),
                            ("integer", "Número Entero"),
                            ("float", "Número Decimal"),
                            ("boolean", "Verdadero/Falso"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del Sistema",
                "verbose_name_plural": "Configuraciones del Sistema",
            },
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=15)),
                ("fecha_ultimo_acceso", models.DateTimeField(blank=True, null=True)),
                ("intentos_login_fallidos", models.IntegerField(default=0)),
                ("cuenta_bloqueada", models.BooleanField(default=False)),
                ("fecha_bloqueo", models.DateTimeField(blank=True, null=True)),
                ("requiere_cambio_password", models.BooleanField(default=False)),
                (
                    "tienda_asignada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tiendas.tienda",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuario",
            },
        ),
    ]
