# Generated by Django 5.2.1 on 2025-05-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="pagado",
            field=models.BooleanField(default=False),
        ),
    ]
