# Generated by Django 5.2.1 on 2025-05-29 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0002_add_advanced_order_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="es_pedido_padre",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="fecha_conversion_venta",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="numero_ticket",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="pedido_padre",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="permite_entrega_parcial",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="porcentaje_completado",
        ),
    ]
