# Generated by Django 5.2.1 on 2025-05-29 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0002_add_pagado_field"),
        ("ventas", "0003_remove_pedido_es_pedido_padre_and_more"),
    ]

    operations = []
