# Generated by Django 5.2.1 on 2025-05-29 03:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0004_merge_20250528_2048"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="es_pedido_padre",
            field=models.BooleanField(
                default=False,
                help_text="Indica si es un pedido padre que puede contener pedidos hijos",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="fecha_conversion_venta",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha cuando el pedido se convirtió en venta",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="numero_ticket",
            field=models.CharField(
                blank=True,
                help_text="Número único de ticket para entregas parciales",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="pedido_padre",
            field=models.ForeignKey(
                blank=True,
                help_text="Pedido padre para entregas parciales",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pedidos_hijos",
                to="ventas.pedido",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="permite_entrega_parcial",
            field=models.BooleanField(
                default=True,
                help_text="Permite dividir el pedido en entregas parciales",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="porcentaje_completado",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Porcentaje de completado del pedido",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("activo", "Activo"),
                    ("surtido", "Surtido"),
                    ("venta", "Venta"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
