# Generated by Django 5.2.1 on 2025-05-27 21:07

import configuracion.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionNegocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_negocio",
                    models.CharField(default="Mi Negocio", max_length=200),
                ),
                ("eslogan", models.CharField(blank=True, max_length=300, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo del negocio (JPG, PNG, SVG - máximo 2MB)",
                        null=True,
                        upload_to=configuracion.models.logo_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "svg"]
                            )
                        ],
                    ),
                ),
                (
                    "logo_texto",
                    models.CharField(
                        blank=True,
                        help_text="Texto alternativo cuando no hay logo",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "sidebar_collapsed_default",
                    models.BooleanField(
                        default=False,
                        help_text="Estado por defecto del sidebar (expandido/colapsado)",
                    ),
                ),
                (
                    "sidebar_theme",
                    models.CharField(
                        choices=[
                            ("light", "Claro"),
                            ("dark", "Oscuro"),
                            ("primary", "Color Primario"),
                        ],
                        default="dark",
                        max_length=20,
                    ),
                ),
                (
                    "color_primario",
                    models.CharField(
                        default="#007bff",
                        help_text="Color primario en formato hexadecimal (#000000)",
                        max_length=7,
                    ),
                ),
                (
                    "color_secundario",
                    models.CharField(
                        default="#6c757d",
                        help_text="Color secundario en formato hexadecimal (#000000)",
                        max_length=7,
                    ),
                ),
                ("moneda", models.CharField(default="USD", max_length=10)),
                ("simbolo_moneda", models.CharField(default="$", max_length=5)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "idioma",
                    models.CharField(
                        choices=[("es", "Español"), ("en", "English")],
                        default="es",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configuracion_creada",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configuracion_actualizada",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del Negocio",
                "verbose_name_plural": "Configuraciones del Negocio",
                "db_table": "configuracion_negocio",
            },
        ),
        migrations.CreateModel(
            name="DetallesImpresion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mostrar_logo_impresion", models.BooleanField(default=True)),
                (
                    "texto_encabezado",
                    models.TextField(
                        blank=True,
                        help_text="Texto adicional en el encabezado de impresiones",
                        null=True,
                    ),
                ),
                (
                    "texto_pie_pagina",
                    models.TextField(
                        blank=True,
                        help_text="Texto del pie de página en impresiones",
                        null=True,
                    ),
                ),
                (
                    "mensaje_agradecimiento",
                    models.CharField(
                        default="¡Gracias por su compra!",
                        help_text="Mensaje de agradecimiento en recibos",
                        max_length=200,
                    ),
                ),
                ("incluir_fecha_hora", models.BooleanField(default=True)),
                ("incluir_numero_ticket", models.BooleanField(default=True)),
                ("incluir_vendedor", models.BooleanField(default=True)),
                ("incluir_metodo_pago", models.BooleanField(default=True)),
                ("rfc", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "regimen_fiscal",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "numero_autorizacion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "configuracion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impresion",
                        to="configuracion.configuracionnegocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalles de Impresión",
                "verbose_name_plural": "Detalles de Impresión",
                "db_table": "configuracion_impresion",
            },
        ),
        migrations.CreateModel(
            name="InformacionContacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direccion_linea1",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "direccion_linea2",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("ciudad", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "estado_provincia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "codigo_postal",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("pais", models.CharField(default="México", max_length=100)),
                (
                    "telefono_principal",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "telefono_secundario",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "email_principal",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "email_ventas",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "email_soporte",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("sitio_web", models.URLField(blank=True, null=True)),
                ("facebook", models.URLField(blank=True, null=True)),
                ("instagram", models.URLField(blank=True, null=True)),
                ("twitter", models.URLField(blank=True, null=True)),
                ("whatsapp", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "horario_atencion",
                    models.TextField(
                        blank=True,
                        help_text="Horarios de atención al cliente",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "configuracion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacto",
                        to="configuracion.configuracionnegocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Información de Contacto",
                "verbose_name_plural": "Información de Contacto",
                "db_table": "configuracion_contacto",
            },
        ),
    ]
