# Generated by Django 5.2.1 on 2025-05-29 02:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0005_descuentocliente_created_by_and_more"),
        ("productos", "0003_producto_stock_minimo"),
        ("proveedores", "0002_proveedor_max_return_days_purchaseorder_and_more"),
        ("ventas", "0003_remove_pedido_es_pedido_padre_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalClientePolitica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("contenido", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("POLITICA", "Política"),
                            ("TERMINO", "Término y Condición"),
                            ("FAQ", "Pregunta Frecuente"),
                        ],
                        max_length=10,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "orden_display",
                    models.PositiveIntegerField(
                        default=0, help_text="Orden de visualización"
                    ),
                ),
                ("fecha_vigencia", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Política de Portal",
                "verbose_name_plural": "Políticas de Portal",
                "ordering": ["tipo", "orden_display"],
            },
        ),
        migrations.CreateModel(
            name="EntregaParcial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_entrega",
                    models.CharField(
                        help_text="Ticket único para esta entrega parcial",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "fecha_entrega",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "productos_entregados",
                    models.JSONField(
                        help_text="Lista de productos entregados en esta entrega parcial"
                    ),
                ),
                (
                    "monto_entregado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("metodo_pago", models.CharField(blank=True, max_length=50, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "pedido_nuevo",
                    models.ForeignKey(
                        help_text="Nuevo pedido con productos restantes",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas_parciales_nuevas",
                        to="ventas.pedido",
                    ),
                ),
                (
                    "pedido_original",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas_parciales_originales",
                        to="ventas.pedido",
                    ),
                ),
                (
                    "usuario_entrega",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrega Parcial",
                "verbose_name_plural": "Entregas Parciales",
                "ordering": ["-fecha_entrega"],
            },
        ),
        migrations.CreateModel(
            name="EstadoProductoSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_anterior",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "estado_nuevo",
                    models.CharField(
                        choices=[
                            ("APARTADO", "Apartado en Pedido"),
                            ("RECIBIDO", "Recibido en Tienda"),
                            ("SOLICITADO_PROVEEDOR", "Solicitado a Proveedor"),
                            ("VERIFICADO", "Verificado por Proveedor"),
                            ("EN_ESPERA", "En Espera de Envío"),
                            ("RECIBIDOS_TIENDA", "Recibidos en Tienda"),
                            ("LISTO_ENTREGA", "Listo para Entrega"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "fecha_cambio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True,
                        help_text="Ubicación física del producto",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "detalle_pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos",
                        to="ventas.detallepedido",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Proveedor relacionado con este cambio de estado",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="proveedores.proveedor",
                    ),
                ),
                (
                    "usuario_cambio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguimiento de Estado",
                "verbose_name_plural": "Seguimientos de Estado",
                "ordering": ["-fecha_cambio"],
            },
        ),
        migrations.CreateModel(
            name="NotaCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CREDITO", "Nota de Crédito"),
                            ("DEBITO", "Nota de Débito"),
                        ],
                        max_length=10,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "motivo",
                    models.TextField(help_text="Motivo de la nota de crédito/débito"),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        help_text="Fecha de vencimiento (60 días por defecto)"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVA", "Activa"),
                            ("APLICADA", "Aplicada"),
                            ("VENCIDA", "Vencida"),
                        ],
                        default="ACTIVA",
                        max_length=10,
                    ),
                ),
                ("fecha_aplicacion", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "aplicada_en_pedido",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pedido donde se aplicó esta nota",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_aplicadas",
                        to="ventas.pedido",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notas_credito",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pedido_origen",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pedido que originó esta nota",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_origen",
                        to="ventas.pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Crédito/Débito",
                "verbose_name_plural": "Notas de Crédito/Débito",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrdenCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_orden", models.CharField(max_length=50, unique=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo - Recibiendo Productos"),
                            ("PENDIENTE", "Pendiente - Esperando Surtido"),
                            ("VENTA", "Completado - Convertido a Venta"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="ACTIVO",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "total_productos",
                    models.PositiveIntegerField(
                        default=0, help_text="Total de productos en la orden"
                    ),
                ),
                (
                    "productos_recibidos",
                    models.PositiveIntegerField(
                        default=0, help_text="Productos ya recibidos"
                    ),
                ),
                (
                    "monto_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "anticipos_pagados",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_cliente",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordenes_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordenes_actualizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Cliente",
                "verbose_name_plural": "Órdenes de Cliente",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="ProductoCompartir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plataforma",
                    models.CharField(
                        choices=[
                            ("FACEBOOK", "Facebook"),
                            ("WHATSAPP", "WhatsApp"),
                            ("INSTAGRAM", "Instagram"),
                            ("TWITTER", "Twitter"),
                        ],
                        max_length=15,
                    ),
                ),
                ("url_compartida", models.URLField(blank=True, null=True)),
                (
                    "fecha_compartido",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "clicks_generados",
                    models.PositiveIntegerField(
                        default=0, help_text="Clicks rastreados desde este compartido"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos_compartidos",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compartidos",
                        to="productos.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto Compartido",
                "verbose_name_plural": "Productos Compartidos",
                "ordering": ["-fecha_compartido"],
            },
        ),
    ]
