# Generated by Django 5.2.1 on 2025-05-29 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos_avanzados", "0001_initial"),
    ]

    operations = []
