# Generated by Django 5.2.1 on 2025-05-27 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportePersonalizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("clientes_inactivos", "Clientes sin Movimientos"),
                            ("historial_precios", "Historial de Cambios de Precios"),
                            ("inventario_diario", "Inventario Diario y Traspasos"),
                            ("descuentos_mensuales", "Descuentos Aplicados por Mes"),
                            (
                                "cumplimiento_metas",
                                "Cumplimiento de Metas del Tabulador",
                            ),
                            ("ventas_por_vendedor", "Ventas por Vendedor"),
                            ("productos_mas_vendidos", "Productos Más Vendidos"),
                            ("analisis_rentabilidad", "Análisis de Rentabilidad"),
                            ("stock_critico", "Stock Crítico y Alertas"),
                            ("tendencias_ventas", "Tendencias de Ventas"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("parametros", models.JSONField(blank=True, default=dict)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("ultima_ejecucion", models.DateTimeField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte Personalizado",
                "verbose_name_plural": "Reportes Personalizados",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="EjecucionReporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_ejecucion", models.DateTimeField(auto_now_add=True)),
                ("parametros_utilizados", models.JSONField(default=dict)),
                ("tiempo_ejecucion", models.FloatField(blank=True, null=True)),
                ("registros_encontrados", models.IntegerField(default=0)),
                ("archivo_generado", models.CharField(blank=True, max_length=255)),
                (
                    "ejecutado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ejecuciones",
                        to="reportes.reportepersonalizado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ejecución de Reporte",
                "verbose_name_plural": "Ejecuciones de Reporte",
                "ordering": ["-fecha_ejecucion"],
            },
        ),
    ]
