# Generated by Django 5.2 on 2025-05-01 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
        ('tiendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('propiedad', models.CharField(blank=True, max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_pagina', models.CharField(blank=True, max_length=20)),
                ('temporada', models.CharField(max_length=30)),
                ('oferta', models.BooleanField(default=False)),
                ('admite_devolucion', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='proveedores.proveedor')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='tiendas.tienda')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
