# Generated by Django 5.2 on 2025-05-19 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Catalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("temporada", models.CharField(blank=True, max_length=50, null=True)),
                ("es_oferta", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_inicio_vigencia", models.DateField(blank=True, null=True)),
                ("fecha_fin_vigencia", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="producto",
            name="catalogo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productos",
                to="productos.catalogo",
            ),
        ),
    ]
