# Generated by Django 5.2 on 2025-05-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_catalogo_producto_catalogo"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="stock_minimo",
            field=models.IntegerField(default=5),
        ),
    ]
