# Generated by Django 5.2 on 2025-05-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_reglaprogramalealtad_cliente_max_return_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="monto_acumulado",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
