# Generated by Django 5.2 on 2025-05-21 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_cliente_monto_acumulado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Usuario del sistema asociado a este cliente (para login de distribuidoras)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cliente_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
