# Generated by Django 5.2.1 on 2025-05-26 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0002_caja_cerrada_caja_fondo_inicial_alter_caja_fecha_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaccioncaja",
            name="fecha",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaccioncaja",
            name="referencia",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="transaccioncaja",
            name="tipo_movimiento",
            field=models.CharField(
                choices=[("INGRESO", "Ingreso"), ("EGRESO", "Egreso")], max_length=10
            ),
        ),
    ]
