# Generated by Django 5.2.1 on 2025-05-21 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("tiendas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionSincronizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sincronizacion_automatica", models.BooleanField(default=True)),
                ("intervalo_minutos", models.PositiveIntegerField(default=15)),
                ("ultima_sincronizacion", models.DateTimeField(blank=True, null=True)),
                (
                    "prioridades",
                    models.JSONField(
                        default=dict,
                        help_text='Prioridades por modelo en formato {"app.Modelo": 1}',
                    ),
                ),
                (
                    "estrategias_conflicto",
                    models.JSONField(
                        default=dict,
                        help_text='Estrategias por modelo en formato {"app.Modelo": "central"} o {"app.Modelo": "local"}',
                    ),
                ),
                (
                    "tienda",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_sincronizacion",
                        to="tiendas.tienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Sincronización",
                "verbose_name_plural": "Configuraciones de Sincronización",
            },
        ),
        migrations.CreateModel(
            name="RegistroSincronizacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("operaciones_totales", models.PositiveIntegerField(default=0)),
                ("operaciones_exitosas", models.PositiveIntegerField(default=0)),
                ("operaciones_fallidas", models.PositiveIntegerField(default=0)),
                ("operaciones_con_conflicto", models.PositiveIntegerField(default=0)),
                (
                    "resumen",
                    models.JSONField(
                        default=dict, help_text="Resumen por modelo y operación"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_proceso", "En Proceso"),
                            ("completado", "Completado"),
                            ("error", "Error"),
                            ("conflicto", "Conflicto"),
                        ],
                        default="en_proceso",
                        max_length=20,
                    ),
                ),
                (
                    "iniciado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_sincronizacion",
                        to="tiendas.tienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Sincronización",
                "verbose_name_plural": "Historial de Sincronización",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="ColaSincronizacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.CharField(max_length=255)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "tipo_operacion",
                    models.CharField(
                        choices=[
                            ("crear", "Crear"),
                            ("actualizar", "Actualizar"),
                            ("eliminar", "Eliminar"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_proceso", "En Proceso"),
                            ("completado", "Completado"),
                            ("error", "Error"),
                            ("conflicto", "Conflicto"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("intentos", models.PositiveSmallIntegerField(default=0)),
                (
                    "prioridad",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Menor número = mayor prioridad"
                    ),
                ),
                (
                    "datos",
                    models.JSONField(
                        help_text="Datos serializados del objeto para sincronizar"
                    ),
                ),
                ("tiene_conflicto", models.BooleanField(default=False)),
                ("fecha_resolucion", models.DateTimeField(blank=True, null=True)),
                ("error_mensaje", models.TextField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "resuelto_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conflictos_resueltos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tienda_destino",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tienda destino (nulo si es servidor central)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operaciones_entrantes",
                        to="tiendas.tienda",
                    ),
                ),
                (
                    "tienda_origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operaciones_salientes",
                        to="tiendas.tienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operación de Sincronización",
                "verbose_name_plural": "Cola de Sincronización",
                "ordering": ["prioridad", "fecha_creacion"],
                "indexes": [
                    models.Index(
                        fields=["estado", "tienda_origen"],
                        name="sincronizac_estado_348264_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="sincronizac_content_081632_idx",
                    ),
                ],
            },
        ),
    ]
