# Generated by Django 5.2.1 on 2025-05-21 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("sincronizacion", "0001_initial"),
        ("tiendas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("accion", models.CharField(max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=255, null=True)),
                ("ip_origen", models.GenericIPAddressField(blank=True, null=True)),
                ("detalles", models.JSONField(blank=True, null=True)),
                ("exitoso", models.BooleanField(default=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "tienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auditorias_sincronizacion",
                        to="tiendas.tienda",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditorias_sincronizacion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Auditoría",
                "verbose_name_plural": "Registros de Auditoría",
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(
                        fields=["fecha", "tienda"], name="sincronizac_fecha_eec438_idx"
                    ),
                    models.Index(
                        fields=["usuario", "accion"],
                        name="sincronizac_usuario_dd63be_idx",
                    ),
                ],
            },
        ),
    ]
