# Generated by Django 5.2.1 on 2025-05-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sincronizacion", "0002_create_registro_auditoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="colasincronizacion",
            name="datos_servidor",
            field=models.JSONField(
                blank=True,
                help_text="Datos del servidor en caso de conflicto",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colasincronizacion",
            name="diferencias",
            field=models.JSONField(
                blank=True, help_text="Diferencias detectadas en conflicto", null=True
            ),
        ),
    ]
