# Generated by Django 5.2 on 2025-05-19 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devoluciones", "0001_initial"),
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="devolucion",
            name="detalle_pedido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devoluciones",
                to="ventas.detallepedido",
            ),
        ),
        migrations.AddField(
            model_name="devolucion",
            name="precio_devolucion",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="devolucion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("validada", "Validada"),
                    ("rechazada", "Rechazada"),
                    ("completada", "Completada"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
