# Generated by Django 5.2 on 2025-05-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabuladorDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rango_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
