# Generated by Django 5.2.1 on 2025-06-02 18:53

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proveedores", "0002_proveedor_max_return_days_purchaseorder_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="direccion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="rating_calidad",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.0"),
                help_text="Rating de calidad 1-5",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="rating_puntualidad",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.0"),
                help_text="Rating de puntualidad 1-5",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="telefono",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="tiempo_entrega_promedio",
            field=models.PositiveIntegerField(
                default=7, help_text="Días promedio de entrega"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="anticipo_pagado",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="anticipo_requerido",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="archivos_adjuntos",
            field=models.JSONField(
                blank=True, default=list, help_text="URLs de archivos adjuntos"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="fecha_confirmacion",
            field=models.DateTimeField(
                blank=True, help_text="Cuando el proveedor confirmó la orden", null=True
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="fecha_envio",
            field=models.DateTimeField(
                blank=True,
                help_text="Cuando el proveedor envió los productos",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="fecha_estimada_entrega",
            field=models.DateField(
                blank=True, help_text="Fecha estimada de entrega", null=True
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="fecha_recepcion_completa",
            field=models.DateTimeField(
                blank=True, help_text="Recepción completa", null=True
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="fecha_recepcion_parcial",
            field=models.DateTimeField(
                blank=True, help_text="Primera recepción parcial", null=True
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="fecha_vencimiento",
            field=models.DateField(
                blank=True, help_text="Fecha límite para recibir", null=True
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="monto_total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="numero_orden",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="numero_tracking",
            field=models.CharField(
                blank=True, help_text="Número de seguimiento del envío", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="observaciones",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="prioridad",
            field=models.CharField(
                choices=[
                    ("baja", "Baja"),
                    ("normal", "Normal"),
                    ("alta", "Alta"),
                    ("urgente", "Urgente"),
                ],
                default="normal",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders_actualizadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="cantidad_defectuosa",
            field=models.PositiveIntegerField(
                default=0, help_text="Cantidad recibida con defectos"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="descuento_aplicado",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Descuento en porcentaje",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="fecha_recepcion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="lote_proveedor",
            field=models.CharField(
                blank=True, help_text="Número de lote del proveedor", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="observaciones_item",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="precio_unitario",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("confirmado", "Confirmado por Proveedor"),
                    ("enviado", "Enviado"),
                    ("recibido_parcial", "Recibido Parcial"),
                    ("recibido", "Recibido Completo"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PurchaseOrderTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("creada", "Orden Creada"),
                            ("confirmada", "Confirmada por Proveedor"),
                            ("modificada", "Modificada"),
                            ("enviada", "Enviada por Proveedor"),
                            ("recepcion_parcial", "Recepción Parcial"),
                            ("recepcion_completa", "Recepción Completa"),
                            ("cancelada", "Cancelada"),
                            ("devolucion", "Devolución"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("descripcion", models.TextField()),
                ("datos_adicionales", models.JSONField(blank=True, default=dict)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_history",
                        to="proveedores.purchaseorder",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="ProveedorEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo_inicio", models.DateField()),
                ("periodo_fin", models.DateField()),
                ("ordenes_totales", models.PositiveIntegerField(default=0)),
                ("ordenes_a_tiempo", models.PositiveIntegerField(default=0)),
                ("ordenes_atrasadas", models.PositiveIntegerField(default=0)),
                ("productos_defectuosos", models.PositiveIntegerField(default=0)),
                ("productos_recibidos", models.PositiveIntegerField(default=0)),
                (
                    "calificacion_calidad",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.0"), max_digits=3
                    ),
                ),
                (
                    "calificacion_puntualidad",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.0"), max_digits=3
                    ),
                ),
                (
                    "calificacion_comunicacion",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.0"), max_digits=3
                    ),
                ),
                (
                    "calificacion_precio",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.0"), max_digits=3
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("recomendaciones", models.TextField(blank=True)),
                ("fecha_evaluacion", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones",
                        to="proveedores.proveedor",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_evaluacion"],
                "unique_together": {("proveedor", "periodo_inicio", "periodo_fin")},
            },
        ),
    ]
